export const genres = {
  count: 19,
  next: null,
  previous: null,
  results: [
    {
      id: 4,
      name: "Action",
      slug: "action",
      games_count: 190008,
      image_background:
        "https://media.rawg.io/media/games/46d/46d98e6910fbc0706e2948a7cc9b10c5.jpg",
      games: [
        {
          id: 3498,
          slug: "grand-theft-auto-v",
          name: "Grand Theft Auto V",
          added: 22254,
        },
        {
          id: 3328,
          slug: "the-witcher-3-wild-hunt",
          name: "The Witcher 3: Wild Hunt",
          added: 21930,
        },
        {
          id: 5286,
          slug: "tomb-raider",
          name: "Tomb Raider (2013)",
          added: 17689,
        },
        {
          id: 13536,
          slug: "portal",
          name: "Portal",
          added: 17655,
        },
        {
          id: 12020,
          slug: "left-4-dead-2",
          name: "Left 4 Dead 2",
          added: 17432,
        },
        {
          id: 5679,
          slug: "the-elder-scrolls-v-skyrim",
          name: "The Elder Scrolls V: Skyrim",
          added: 16673,
        },
      ],
    },
    {
      id: 51,
      name: "Indie",
      slug: "indie",
      games_count: 83628,
      image_background:
        "https://media.rawg.io/media/games/e04/e04963f3ac4c4fa83a1dc0b9231e50db.jpg",
      games: [
        {
          id: 1030,
          slug: "limbo",
          name: "Limbo",
          added: 14062,
        },
        {
          id: 422,
          slug: "terraria",
          name: "Terraria",
          added: 13446,
        },
        {
          id: 3272,
          slug: "rocket-league",
          name: "Rocket League",
          added: 12806,
        },
        {
          id: 9767,
          slug: "hollow-knight",
          name: "Hollow Knight",
          added: 11705,
        },
        {
          id: 654,
          slug: "stardew-valley",
          name: "Stardew Valley",
          added: 10898,
        },
        {
          id: 3612,
          slug: "hotline-miami",
          name: "Hotline Miami",
          added: 10851,
        },
      ],
    },
    {
      id: 3,
      name: "Adventure",
      slug: "adventure",
      games_count: 150144,
      image_background:
        "https://media.rawg.io/media/games/d7d/d7d33daa1892e2468cd0263d5dfc957e.jpg",
      games: [
        {
          id: 3439,
          slug: "life-is-strange-episode-1-2",
          name: "Life is Strange",
          added: 15832,
        },
        {
          id: 1030,
          slug: "limbo",
          name: "Limbo",
          added: 14062,
        },
        {
          id: 23027,
          slug: "the-walking-dead",
          name: "The Walking Dead: Season 1",
          added: 11630,
        },
        {
          id: 41,
          slug: "little-nightmares",
          name: "Little Nightmares",
          added: 11596,
        },
        {
          id: 19487,
          slug: "alan-wake",
          name: "Alan Wake",
          added: 10421,
        },
        {
          id: 9721,
          slug: "garrys-mod",
          name: "Garry's Mod",
          added: 10413,
        },
      ],
    },
    {
      id: 5,
      name: "RPG",
      slug: "role-playing-games-rpg",
      games_count: 61208,
      image_background:
        "https://media.rawg.io/media/games/5a4/5a44112251d70a25291cc33757220fce.jpg",
      games: [
        {
          id: 3328,
          slug: "the-witcher-3-wild-hunt",
          name: "The Witcher 3: Wild Hunt",
          added: 21930,
        },
        {
          id: 5679,
          slug: "the-elder-scrolls-v-skyrim",
          name: "The Elder Scrolls V: Skyrim",
          added: 16673,
        },
        {
          id: 802,
          slug: "borderlands-2",
          name: "Borderlands 2",
          added: 15918,
        },
        {
          id: 3070,
          slug: "fallout-4",
          name: "Fallout 4",
          added: 14175,
        },
        {
          id: 41494,
          slug: "cyberpunk-2077",
          name: "Cyberpunk 2077",
          added: 13733,
        },
        {
          id: 766,
          slug: "warframe",
          name: "Warframe",
          added: 13104,
        },
      ],
    },
    {
      id: 10,
      name: "Strategy",
      slug: "strategy",
      games_count: 61666,
      image_background:
        "https://media.rawg.io/media/games/651/651ae84f2d5e36206aad90976a453329.jpg",
      games: [
        {
          id: 10243,
          slug: "company-of-heroes-2",
          name: "Company of Heroes 2",
          added: 9871,
        },
        {
          id: 13633,
          slug: "civilization-v",
          name: "Sid Meier's Civilization V",
          added: 9748,
        },
        {
          id: 11147,
          slug: "ark-survival-of-the-fittest",
          name: "ARK: Survival Of The Fittest",
          added: 8918,
        },
        {
          id: 10065,
          slug: "cities-skylines",
          name: "Cities: Skylines",
          added: 8626,
        },
        {
          id: 13910,
          slug: "xcom-enemy-unknown",
          name: "XCOM: Enemy Unknown",
          added: 8497,
        },
        {
          id: 5525,
          slug: "brutal-legend",
          name: "Brutal Legend",
          added: 8406,
        },
      ],
    },
    {
      id: 2,
      name: "Shooter",
      slug: "shooter",
      games_count: 59595,
      image_background:
        "https://media.rawg.io/media/games/15c/15c95a4915f88a3e89c821526afe05fc.jpg",
      games: [
        {
          id: 4200,
          slug: "portal-2",
          name: "Portal 2",
          added: 20705,
        },
        {
          id: 4291,
          slug: "counter-strike-global-offensive",
          name: "Counter-Strike: Global Offensive",
          added: 18316,
        },
        {
          id: 12020,
          slug: "left-4-dead-2",
          name: "Left 4 Dead 2",
          added: 17432,
        },
        {
          id: 4062,
          slug: "bioshock-infinite",
          name: "BioShock Infinite",
          added: 16006,
        },
        {
          id: 13537,
          slug: "half-life-2",
          name: "Half-Life 2",
          added: 15958,
        },
        {
          id: 802,
          slug: "borderlands-2",
          name: "Borderlands 2",
          added: 15918,
        },
      ],
    },
    {
      id: 40,
      name: "Casual",
      slug: "casual",
      games_count: 65883,
      image_background:
        "https://media.rawg.io/media/games/3ef/3eff92562640e452d3487c04ba6d7fae.jpg",
      games: [
        {
          id: 9721,
          slug: "garrys-mod",
          name: "Garry's Mod",
          added: 10413,
        },
        {
          id: 326292,
          slug: "fall-guys",
          name: "Fall Guys: Ultimate Knockout",
          added: 8891,
        },
        {
          id: 9830,
          slug: "brawlhalla",
          name: "Brawlhalla",
          added: 8263,
        },
        {
          id: 356714,
          slug: "among-us",
          name: "Among Us",
          added: 7898,
        },
        {
          id: 817974,
          slug: "wallpaper-engine",
          name: "Wallpaper Engine",
          added: 6539,
        },
        {
          id: 42187,
          slug: "the-sims-4",
          name: "The Sims 4",
          added: 6518,
        },
      ],
    },
    {
      id: 14,
      name: "Simulation",
      slug: "simulation",
      games_count: 75858,
      image_background:
        "https://media.rawg.io/media/screenshots/f2f/f2f3c93d6153da7aee590f3ab8ccd803.jpg",
      games: [
        {
          id: 654,
          slug: "stardew-valley",
          name: "Stardew Valley",
          added: 10898,
        },
        {
          id: 10035,
          slug: "hitman",
          name: "Hitman",
          added: 10852,
        },
        {
          id: 9721,
          slug: "garrys-mod",
          name: "Garry's Mod",
          added: 10413,
        },
        {
          id: 9882,
          slug: "dont-starve-together",
          name: "Don't Starve Together",
          added: 9926,
        },
        {
          id: 22509,
          slug: "minecraft",
          name: "Minecraft",
          added: 8793,
        },
        {
          id: 10065,
          slug: "cities-skylines",
          name: "Cities: Skylines",
          added: 8626,
        },
      ],
    },
    {
      id: 7,
      name: "Puzzle",
      slug: "puzzle",
      games_count: 97362,
      image_background:
        "https://media.rawg.io/media/games/9f4/9f418898f5415668ca47b5f4ab1ecfeb.jpg",
      games: [
        {
          id: 4200,
          slug: "portal-2",
          name: "Portal 2",
          added: 20705,
        },
        {
          id: 13536,
          slug: "portal",
          name: "Portal",
          added: 17655,
        },
        {
          id: 1030,
          slug: "limbo",
          name: "Limbo",
          added: 14062,
        },
        {
          id: 19709,
          slug: "half-life-2-episode-two",
          name: "Half-Life 2: Episode Two",
          added: 11251,
        },
        {
          id: 1450,
          slug: "inside",
          name: "INSIDE",
          added: 8319,
        },
        {
          id: 3853,
          slug: "trine-2-complete-story",
          name: "Trine 2: Complete Story",
          added: 7421,
        },
      ],
    },
    {
      id: 11,
      name: "Arcade",
      slug: "arcade",
      games_count: 22668,
      image_background:
        "https://media.rawg.io/media/games/a5a/a5abaa1b5cc1567b026fa3aa9fbd828e.jpg",
      games: [
        {
          id: 3612,
          slug: "hotline-miami",
          name: "Hotline Miami",
          added: 10851,
        },
        {
          id: 17540,
          slug: "injustice-gods-among-us-ultimate-edition",
          name: "Injustice: Gods Among Us Ultimate Edition",
          added: 9845,
        },
        {
          id: 22509,
          slug: "minecraft",
          name: "Minecraft",
          added: 8793,
        },
        {
          id: 4003,
          slug: "grid-2",
          name: "GRID 2",
          added: 7714,
        },
        {
          id: 3408,
          slug: "hotline-miami-2-wrong-number",
          name: "Hotline Miami 2: Wrong Number",
          added: 6414,
        },
        {
          id: 58753,
          slug: "forza-horizon-4",
          name: "Forza Horizon 4",
          added: 6292,
        },
      ],
    },
    {
      id: 83,
      name: "Platformer",
      slug: "platformer",
      games_count: 100901,
      image_background:
        "https://media.rawg.io/media/games/718/71891d2484a592d871e91dc826707e1c.jpg",
      games: [
        {
          id: 1030,
          slug: "limbo",
          name: "Limbo",
          added: 14062,
        },
        {
          id: 422,
          slug: "terraria",
          name: "Terraria",
          added: 13446,
        },
        {
          id: 9767,
          slug: "hollow-knight",
          name: "Hollow Knight",
          added: 11705,
        },
        {
          id: 41,
          slug: "little-nightmares",
          name: "Little Nightmares",
          added: 11596,
        },
        {
          id: 3144,
          slug: "super-meat-boy",
          name: "Super Meat Boy",
          added: 9676,
        },
        {
          id: 17572,
          slug: "batman-aa-goty",
          name: "Batman: Arkham Asylum Game of the Year Edition",
          added: 8558,
        },
      ],
    },
    {
      id: 59,
      name: "Massively Multiplayer",
      slug: "massively-multiplayer",
      games_count: 4188,
      image_background:
        "https://media.rawg.io/media/games/11f/11fd681c312c14644ab360888dba3486.jpg",
      games: [
        {
          id: 10213,
          slug: "dota-2",
          name: "Dota 2",
          added: 13119,
        },
        {
          id: 766,
          slug: "warframe",
          name: "Warframe",
          added: 13104,
        },
        {
          id: 10142,
          slug: "playerunknowns-battlegrounds",
          name: "PlayerUnknown’s Battlegrounds",
          added: 10675,
        },
        {
          id: 10533,
          slug: "path-of-exile",
          name: "Path of Exile",
          added: 10617,
        },
        {
          id: 362,
          slug: "for-honor",
          name: "For Honor",
          added: 9663,
        },
        {
          id: 11147,
          slug: "ark-survival-of-the-fittest",
          name: "ARK: Survival Of The Fittest",
          added: 8918,
        },
      ],
    },
    {
      id: 1,
      name: "Racing",
      slug: "racing",
      games_count: 25663,
      image_background:
        "https://media.rawg.io/media/games/78d/78dfae12fb8c5b16cd78648553071e0a.jpg",
      games: [
        {
          id: 3272,
          slug: "rocket-league",
          name: "Rocket League",
          added: 12806,
        },
        {
          id: 4003,
          slug: "grid-2",
          name: "GRID 2",
          added: 7714,
        },
        {
          id: 2572,
          slug: "dirt-rally",
          name: "DiRT Rally",
          added: 7006,
        },
        {
          id: 58753,
          slug: "forza-horizon-4",
          name: "Forza Horizon 4",
          added: 6292,
        },
        {
          id: 5578,
          slug: "grid",
          name: "GRID (2008)",
          added: 5421,
        },
        {
          id: 19491,
          slug: "burnout-paradise-the-ultimate-box",
          name: "Burnout Paradise: The Ultimate Box",
          added: 4847,
        },
      ],
    },
    {
      id: 15,
      name: "Sports",
      slug: "sports",
      games_count: 22494,
      image_background:
        "https://media.rawg.io/media/games/9e5/9e52a797f049e701d4eee84774a99007.jpg",
      games: [
        {
          id: 3272,
          slug: "rocket-league",
          name: "Rocket League",
          added: 12806,
        },
        {
          id: 326292,
          slug: "fall-guys",
          name: "Fall Guys: Ultimate Knockout",
          added: 8891,
        },
        {
          id: 2572,
          slug: "dirt-rally",
          name: "DiRT Rally",
          added: 7006,
        },
        {
          id: 53341,
          slug: "jet-set-radio-2012",
          name: "Jet Set Radio",
          added: 5304,
        },
        {
          id: 9575,
          slug: "vrchat",
          name: "VRChat",
          added: 5120,
        },
        {
          id: 36,
          slug: "tekken-7",
          name: "TEKKEN 7",
          added: 4186,
        },
      ],
    },
    {
      id: 6,
      name: "Fighting",
      slug: "fighting",
      games_count: 11772,
      image_background:
        "https://media.rawg.io/media/screenshots/5a1/5a1ce6908dc401fa9f805d5db4e832d7.jpg",
      games: [
        {
          id: 17540,
          slug: "injustice-gods-among-us-ultimate-edition",
          name: "Injustice: Gods Among Us Ultimate Edition",
          added: 9845,
        },
        {
          id: 108,
          slug: "mortal-kombat-x",
          name: "Mortal Kombat X",
          added: 9001,
        },
        {
          id: 28179,
          slug: "sega-mega-drive-and-genesis-classics",
          name: "SEGA Mega Drive and Genesis Classics",
          added: 8409,
        },
        {
          id: 9830,
          slug: "brawlhalla",
          name: "Brawlhalla",
          added: 8263,
        },
        {
          id: 274480,
          slug: "mortal-kombat-11",
          name: "Mortal Kombat 11",
          added: 5702,
        },
        {
          id: 44525,
          slug: "yakuza-kiwami",
          name: "Yakuza Kiwami",
          added: 4707,
        },
      ],
    },
    {
      id: 19,
      name: "Family",
      slug: "family",
      games_count: 5408,
      image_background:
        "https://media.rawg.io/media/games/9a1/9a18c226cf379272c698f26d2b79b3da.jpg",
      games: [
        {
          id: 3254,
          slug: "journey",
          name: "Journey",
          added: 8585,
        },
        {
          id: 3729,
          slug: "lego-the-hobbit",
          name: "LEGO The Hobbit",
          added: 5471,
        },
        {
          id: 3350,
          slug: "broken-age",
          name: "Broken Age",
          added: 5136,
        },
        {
          id: 1259,
          slug: "machinarium",
          name: "Machinarium",
          added: 4747,
        },
        {
          id: 1140,
          slug: "world-of-goo",
          name: "World of Goo",
          added: 4596,
        },
        {
          id: 4331,
          slug: "sonic-generations",
          name: "Sonic Generations",
          added: 4313,
        },
      ],
    },
    {
      id: 28,
      name: "Board Games",
      slug: "board-games",
      games_count: 8389,
      image_background:
        "https://media.rawg.io/media/games/0e7/0e7582dda5530d5b95f877dfad57e6ba.jpg",
      games: [
        {
          id: 23557,
          slug: "gwent-the-witcher-card-game",
          name: "Gwent: The Witcher Card Game",
          added: 5056,
        },
        {
          id: 327999,
          slug: "dota-underlords",
          name: "Dota Underlords",
          added: 4253,
        },
        {
          id: 2055,
          slug: "adventure-capitalist",
          name: "AdVenture Capitalist",
          added: 3573,
        },
        {
          id: 758,
          slug: "hue",
          name: "Hue",
          added: 2810,
        },
        {
          id: 3187,
          slug: "armello",
          name: "Armello",
          added: 2124,
        },
        {
          id: 2306,
          slug: "poker-night-2",
          name: "Poker Night 2",
          added: 2114,
        },
      ],
    },
    {
      id: 17,
      name: "Card",
      slug: "card",
      games_count: 4537,
      image_background:
        "https://media.rawg.io/media/games/742/7424c1f7d0a8da9ae29cd866f985698b.jpg",
      games: [
        {
          id: 28121,
          slug: "slay-the-spire",
          name: "Slay the Spire",
          added: 5225,
        },
        {
          id: 23557,
          slug: "gwent-the-witcher-card-game",
          name: "Gwent: The Witcher Card Game",
          added: 5056,
        },
        {
          id: 18852,
          slug: "poker-night-at-the-inventory",
          name: "Poker Night at the Inventory",
          added: 2816,
        },
        {
          id: 332,
          slug: "the-elder-scrolls-legends",
          name: "The Elder Scrolls: Legends",
          added: 2279,
        },
        {
          id: 8923,
          slug: "faeria",
          name: "Faeria",
          added: 2229,
        },
        {
          id: 2306,
          slug: "poker-night-2",
          name: "Poker Night 2",
          added: 2114,
        },
      ],
    },
    {
      id: 34,
      name: "Educational",
      slug: "educational",
      games_count: 15694,
      image_background:
        "https://media.rawg.io/media/screenshots/49d/49dae660a0fc843b23d63af8ce34e33c.jpg",
      games: [
        {
          id: 1358,
          slug: "papers-please",
          name: "Papers, Please",
          added: 7215,
        },
        {
          id: 1140,
          slug: "world-of-goo",
          name: "World of Goo",
          added: 4596,
        },
        {
          id: 2778,
          slug: "surgeon-simulator-cpr",
          name: "Surgeon Simulator",
          added: 4080,
        },
        {
          id: 9768,
          slug: "gameguru",
          name: "GameGuru",
          added: 2674,
        },
        {
          id: 13777,
          slug: "sid-meiers-civilization-iv-colonization",
          name: "Sid Meier's Civilization IV: Colonization",
          added: 2423,
        },
        {
          id: 6885,
          slug: "pirates-3",
          name: "Sid Meier's Pirates!",
          added: 2357,
        },
      ],
    },
  ],
};
