import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from '@/components/navbar'
import { Providers } from "./provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="bg-[#070F2B]">
        <Providers>
          <div>
            <Navbar />

            {children}

            <footer>footer</footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
