import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from '@/components/navbar'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className="bg-[#070F2B]"
      >
        <Navbar />

        {children}

        <footer>footer</footer>
      </body>
    </html>
  );
}
